### ISSUE TITLE
Proteus doesn't seem to work in Safari?

### ISSUE THREAD

**Issue by jjfiv** [CIIR/Proteus#118]
Couldn't figure out how to open the JS console, but @carobuck got some weird error on her laptop.

**Comment by mzarozinski** [comment]
This was caused by the query:

         recipe: "fish"

Galago/Proteus didn't like the space between the colon and the double quote and responded with:

       Error: ``0``

Stack trace:

java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lemurproject.galago.core.retrieval.query.SimpleQuery.parseTree(SimpleQuery.java:212)
	at ciir.proteus.server.action.JSONSearch.handle(JSONSearch.java:119)
	at ciir.proteus.server.HTTPRouter.handleJSON(HTTPRouter.java:204)
	at ciir.proteus.server.HTTPRouter.handleJSON(HTTPRouter.java:195)
	at ciir.proteus.server.HTTPRouter.handle(HTTPRouter.java:182)
	at org.lemurproject.galago.tupleflow.web.WebServer$JettyHandler.handle(WebServer.java:100)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
